language: rust
rust:
  - 1.20.0
  - stable
matrix:
  include:
    rust: nightly
    script:
      - cargo build --features 'nightly' --verbose
      - cargo test --features 'nightly' --verbose
notifications:
  email:
    on_success: never
